### ISSUE TITLE
[Feature] Add missing host key hash types

### ISSUE THREAD

**Issue by pkittenis** [ParallelSSH/ssh2-python#137]
`LIBSSH2_HOSTKEY_HASH_SHA256` is missing from `ssh2.session`, possibly other hash types.

**Comment by pkittenis** [comment]
Resolved by #138

**Comment by radha-wadhera** [comment]
Thanks for considering this change. I am trying to upgrade the ssh2-python but I am still not able to get SHA 256

Version installed on my version
ssh2-python==0.25.0

I am getting the following error
**exception module 'ssh2.session' has no attribute 'LIBSSH2_HOSTKEY_HASH_SHA256'**

I even tried with version 0.24.0. But no luck! Can you please help me out with this?

**Comment by radha-wadhera** [comment]
I missed telling that I am **_still getting the error of missing attribute when I am trying to use the following API_**

**nodekey_hash = _session.hostkey_hash_(ssh2.session.LIBSSH2_HOSTKEY_HASH_SHA256)** 
The version installed on my system
**ssh2-python==0.25.0**

I am getting the following error
**exception module 'ssh2.session' has no attribute 'LIBSSH2_HOSTKEY_HASH_SHA256'**

Can you please help me out with this?

**Comment by pkittenis** [comment]
`from ssh2.session import LIBSSH2_HOSTKEY_HASH_SHA256` works.

Please raise a new issue with steps to reproduce if there is an issue with the library. This issue is closed.
