### ISSUE TITLE
ssh2.session.Session.userauth_publickey_frommemory() - TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by PhenomPBG** [ParallelSSH/ssh2-python#86]
```
host = "127.0.0.1"
port = 22
user_name = "user"
privatekey_data = "..."
passphrase = ""

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((host, port))
session = Session()
session.handshake(s)

session.userauth_publickey_frommemory(user_name, privatekey_data.encode('ascii'), passphrase=passphrase)
```

Last line from stack trace:

File "ssh2/session.pyx", line 240, in ssh2.session.Session.userauth_publickey_frommemory
TypeError: object of type 'NoneType' has no len()

Seems like the optional argument publickeyfiledata defaults to None, but its len() is always checked anyway.

Tested on both 0.17 and 0.18 with Python 3.7.1 on CentOS 7.

**Comment by PhenomPBG** [comment]
Cleaned up the sample code a bit.

**Comment by j3pic** [comment]
@PhenomPBG the bug remains. #90 doesn't fix it either. I've made a new PR that should fix it.

**Comment by PhenomPBG** [comment]
> @PhenomPBG the bug remains. #90 doesn't fix it either. I've made a new PR that should fix it.

Thanks!

**Comment by Red-M** [comment]
I'll take a look into why this isn't picked up via the unit tests and correct that, then fix the issue itself.

**Comment by Red-M** [comment]
I know this isn't an amazing answer but I can't replicate this issue with #90 using the same arguments passed inside of a unit test.

Sadly this repository is over the limit for git LFS usage so the builds won't work, so I've managed to bypass LFS for now inside the builds.

Travis is returning no errors for this particular issue.

@j3pic I'm happy to take patches on my fork just because right now it appears that @pkittenis isn't around.

**Comment by j3pic** [comment]
@Red-M Will your fork become the version of `ssh2-python` that installs from PyPI?

**Comment by Red-M** [comment]
I'd hope my fork gets merged into `ssh2-python` as its all there in #90 to merge back in.
I may need to release all the changes under another pypi package name.

**Comment by j3pic** [comment]
There's another problem with my patch: It doesn't compile under Python 3.7 and higher because the C source files were built with the wrong version of Cython (but if I upgrade and generate the C files again, they'll be incompatible with Python 3.6 and below.

**Comment by Red-M** [comment]
What version should they be built against?
I still can't replicate the issue under #90 as it has guards in place if the public key isn't provided with the private key.

**Comment by Red-M** [comment]
My fork has every version building plus 3.8, https://travis-ci.com/Red-M/ssh2-python/builds/141552354

**Comment by j3pic** [comment]
@Red-M Reading the code for #90 it looks like this bug should be fixed there. I'm not sure why I still saw it when I tested manually. Probably because of the bug in Pip I found that affects the use of Git repos from requirements.txt. There's a nonzero chance I was still running the version of ssh2-python from PyPI.

**Comment by basegodfelix** [comment]
still experiencing this issue.

On a side note, if I use the same key and auth from file, it works. Same error thrown as above poster:

File "ssh2/session.pyx", line 237, in ssh2.session.Session.userauth_publickey_frommemory
TypeError: object of type 'NoneType' has no len()


Private key provided

**Comment by kdart** [comment]
A workaround that seems to work for me is to set the publickeyfiledata to an empty bytestring (`b''`).
